{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.mobile.quirks.qualcomm.sdm845-audio;
  inherit (lib) mkIf mkOption types;
in
{
  options.mobile.quirks.qualcomm.sdm845-audio = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Enable audio quirks for SDM845 devices
        Includes q6voiced for modem audio and hexagonrpc for DSP
      '';
    };
    q6voiced = {
      card = mkOption {
        type = types.int;
        default = 0;
        description = "ALSA card number for q6voiced";
      };
      device = mkOption {
        type = types.int;
        default = 6;
        description = "ALSA device number for q6voiced";
      };
    };
    hexagonrpc-fw-dir = mkOption {
      type = types.path;
      default = "/usr/share/qcom/sdm845/OnePlus/oneplus6";
      description = "Firmware directory for hexagonrpcd";
    };
  };

  config = mkIf cfg.enable {
    systemd.services = {
      hexagonrpcd = {
        description = "Hexagon DSP daemon for FastRPC";
        wantedBy = [ "multi-user.target" ];
        after = [ "remote-fs.target" ];
        serviceConfig = {
          ExecStart = "${pkgs.hexagonrpc}/bin/hexagonrpcd -f /dev/fastrpc-adsp -s -R ${cfg.hexagonrpc-fw-dir}";
          Restart = "always";
          RestartSec = "5";
        };
      };
    };

    environment.etc."wireplumber/wireplumber.conf.d/51-qcom-sdm845.conf" = {
      text = ''
        # SDM845 audio configuration for WirePlumber
        # This file is automatically generated by mobile-nixos
      '';
    };
  };
}
